// <auto-generated />
using System;
using FloraAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloraAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227233146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloraAI.Models.DiagnosisRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicDiseaseLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DiagnosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiseaseLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlantNameInput")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TreatmentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserPlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPlantId");

                    b.ToTable("DiagnosisRecords");
                });

            modelBuilder.Entity("FloraAI.Models.PlantLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BaseWateringDays")
                        .HasColumnType("int");

                    b.Property<string>("CareTips")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FertilizingInstructions")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SunlightRequirement")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WateringInstructions")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlantLibrary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicName = "نبتة البوثوس",
                            BaseWateringDays = 7,
                            CareTips = "نبتة مثالية للمبتدئين. تتحمّل الإهمال وتُنقّي الهواء.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد سائل متوازن مرة كل شهر خلال الربيع والصيف.",
                            IsAiGenerated = false,
                            Name = "pothos",
                            SunlightRequirement = "ضوء خافت إلى متوسط.",
                            WateringInstructions = "كل 7 أيام — اترك التربة تجف جزئياً بين الريّات."
                        },
                        new
                        {
                            Id = 2,
                            ArabicName = "نبتة المونستيرا",
                            BaseWateringDays = 7,
                            CareTips = "امسحي الأوراق بقطعة قماش رطبة شهرياً. تحتاج عمود داعم كلما كبرت.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد سائل غني بالنيتروجين كل 3 أسابيع في موسم النمو.",
                            IsAiGenerated = false,
                            Name = "monstera",
                            SunlightRequirement = "ضوء غير مباشر ساطع.",
                            WateringInstructions = "كل 7-5 أيام عندما تجف التربة العلوية."
                        },
                        new
                        {
                            Id = 3,
                            ArabicName = "نبتة الثعبان",
                            BaseWateringDays = 14,
                            CareTips = "من أقوى النباتات الداخلية. لا تتركيها في ماء راكد.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد خفيف مرة في الربيع ومرة في الصيف فقط.",
                            IsAiGenerated = false,
                            Name = "snake plant",
                            SunlightRequirement = "تتأقلم مع أي إضاءة.",
                            WateringInstructions = "كل 14 يوماً صيفاً وكل 3-4 أسابيع شتاءً."
                        },
                        new
                        {
                            Id = 4,
                            ArabicName = "زنبق السلام",
                            BaseWateringDays = 7,
                            CareTips = "تترهّل أوراقها عند العطش وترتفع بعد الري مباشرة.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد سائل شامل كل 6 أسابيع خلال موسم النمو.",
                            IsAiGenerated = false,
                            Name = "peace lily",
                            SunlightRequirement = "ضوء خافت إلى متوسط.",
                            WateringInstructions = "كل 7 أيام أو عند بدء ترهّل الأوراق قليلاً."
                        },
                        new
                        {
                            Id = 5,
                            ArabicName = "نبتة التين كمنجة",
                            BaseWateringDays = 7,
                            CareTips = "حساسة للتحريك والتيارات الهوائية. اختاري مكاناً ثابتاً.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد سائل للنباتات الورقية كل 4 أسابيع.",
                            IsAiGenerated = false,
                            Name = "fiddle leaf fig",
                            SunlightRequirement = "ضوء غير مباشر ساطع لساعات طويلة.",
                            WateringInstructions = "كل 7 أيام — تأكّد من جفاف الطبقة العلوية قبل الري."
                        },
                        new
                        {
                            Id = 6,
                            ArabicName = "نبتة العنكبوت",
                            BaseWateringDays = 7,
                            CareTips = "حساسة لمياه الفلور — استخدمي ماء مفلتراً.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد متوازن كل شهرين في موسم النمو.",
                            IsAiGenerated = false,
                            Name = "spider plant",
                            SunlightRequirement = "ضوء متوسط إلى ساطع غير مباشر.",
                            WateringInstructions = "كل 7 أيام صيفاً وكل 10-14 يوماً شتاءً."
                        },
                        new
                        {
                            Id = 7,
                            ArabicName = "نبتة المطاط",
                            BaseWateringDays = 10,
                            CareTips = "امسحي الأوراق اللامعة بقطعة رطبة. قلّلي الري في الشتاء.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد سائل مخفّف كل 4 أسابيع في موسم النمو.",
                            IsAiGenerated = false,
                            Name = "rubber plant",
                            SunlightRequirement = "ضوء غير مباشر ساطع.",
                            WateringInstructions = "كل 10 أيام صيفاً وكل أسبوعين شتاءً."
                        },
                        new
                        {
                            Id = 8,
                            ArabicName = "صبار الألوفيرا",
                            BaseWateringDays = 14,
                            CareTips = "تربة مفككة سريعة التصريف. تعفّن الجذور هو أكبر خطر عليها.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد خاص بالصبار مرة في الربيع فقط.",
                            IsAiGenerated = false,
                            Name = "aloe vera",
                            SunlightRequirement = "ضوء مباشر أو غير مباشر ساطع.",
                            WateringInstructions = "كل 14 يوماً — جفاف كامل للتربة قبل الري."
                        },
                        new
                        {
                            Id = 9,
                            ArabicName = "نبتة الزد زد",
                            BaseWateringDays = 14,
                            CareTips = "بطيئة النمو لكنها قوية جداً. تنمو في أي بيئة تقريباً.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد خفيف مرة كل موسم نمو.",
                            IsAiGenerated = false,
                            Name = "zz plant",
                            SunlightRequirement = "تتأقلم مع الإضاءة الخافتة.",
                            WateringInstructions = "كل 14 يوماً — تخزّن الماء في جذورها."
                        },
                        new
                        {
                            Id = 10,
                            ArabicName = "نبتة الكاليثيا",
                            BaseWateringDays = 5,
                            CareTips = "استخدمي ماء مفلتراً دائماً. رشّي الأوراق لرفع الرطوبة.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد سائل خفيف الجرعة كل 4 أسابيع في موسم النمو.",
                            IsAiGenerated = false,
                            Name = "calathea",
                            SunlightRequirement = "ضوء خافت إلى متوسط.",
                            WateringInstructions = "كل 5 أيام — رطوبة منتظمة بدون تشبّع."
                        },
                        new
                        {
                            Id = 11,
                            ArabicName = "نبتة الفيكس",
                            BaseWateringDays = 7,
                            CareTips = "تتساقط أوراقها عند تحريكها. اختاري مكاناً ثابتاً.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد سائل شامل كل 4 أسابيع في موسم النمو.",
                            IsAiGenerated = false,
                            Name = "ficus",
                            SunlightRequirement = "ضوء غير مباشر ساطع.",
                            WateringInstructions = "كل 7 أيام — اتركي التربة تجف قليلاً بين الريّات."
                        },
                        new
                        {
                            Id = 12,
                            ArabicName = "نبتة الفيلودندرون",
                            BaseWateringDays = 7,
                            CareTips = "سريعة النمو. تتدلّى بشكل جميل من على الرفوف.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد غني بالنيتروجين كل 3-4 أسابيع موسم النمو.",
                            IsAiGenerated = false,
                            Name = "philodendron",
                            SunlightRequirement = "ضوء متوسط غير مباشر.",
                            WateringInstructions = "كل 7 أيام — 3-4 سم من التربة العلوية تجف بين الريّات."
                        },
                        new
                        {
                            Id = 13,
                            ArabicName = "زهرة الأوركيد",
                            BaseWateringDays = 7,
                            CareTips = "لا تتركي الماء على الأوراق. تحتاج فرق حرارة ليلي/نهاري للإزهار.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد خاص بالأوركيد بنصف الجرعة كل أسبوعين.",
                            IsAiGenerated = false,
                            Name = "orchid",
                            SunlightRequirement = "ضوء غير مباشر ساطع.",
                            WateringInstructions = "كل 7 أيام بغمر الإناء في ماء الغرفة 15 دقيقة ثم تصريفه."
                        },
                        new
                        {
                            Id = 14,
                            ArabicName = "النباتات العصارية",
                            BaseWateringDays = 14,
                            CareTips = "التربة المفككة شرط أساسي. الإفراط في الري هو أول قاتل لها.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد خاص بالصبار مرة في الربيع ومرة في الصيف.",
                            IsAiGenerated = false,
                            Name = "succulents",
                            SunlightRequirement = "ضوء مباشر لعدة ساعات يومياً.",
                            WateringInstructions = "كل 14 يوماً صيفاً وكل 4-6 أسابيع شتاءً."
                        },
                        new
                        {
                            Id = 15,
                            ArabicName = "سرخس بوسطن",
                            BaseWateringDays = 3,
                            CareTips = "رشّي الأوراق يومياً أو ضعيها بجانب صينية ماء لرفع الرطوبة.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FertilizingInstructions = "سماد سائل متوازن مخفّف كل 4 أسابيع في موسم النمو.",
                            IsAiGenerated = false,
                            Name = "boston fern",
                            SunlightRequirement = "ضوء متوسط غير مباشر.",
                            WateringInstructions = "كل 3 أيام — لا تتركيها تجف أبداً."
                        });
                });

            modelBuilder.Entity("FloraAI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FloraAI.Models.UserPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextWateringDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlantLibraryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantLibraryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlants");
                });

            modelBuilder.Entity("FloraAI.Models.DiagnosisRecord", b =>
                {
                    b.HasOne("FloraAI.Models.User", "User")
                        .WithMany("DiagnosisRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloraAI.Models.UserPlant", "UserPlant")
                        .WithMany("DiagnosisRecords")
                        .HasForeignKey("UserPlantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");

                    b.Navigation("UserPlant");
                });

            modelBuilder.Entity("FloraAI.Models.UserPlant", b =>
                {
                    b.HasOne("FloraAI.Models.PlantLibrary", "PlantLibrary")
                        .WithMany("UserPlants")
                        .HasForeignKey("PlantLibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloraAI.Models.User", "User")
                        .WithMany("UserPlants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantLibrary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloraAI.Models.PlantLibrary", b =>
                {
                    b.Navigation("UserPlants");
                });

            modelBuilder.Entity("FloraAI.Models.User", b =>
                {
                    b.Navigation("DiagnosisRecords");

                    b.Navigation("UserPlants");
                });

            modelBuilder.Entity("FloraAI.Models.UserPlant", b =>
                {
                    b.Navigation("DiagnosisRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
